# Compass Config
preferred_syntax = :sass
http_path = '/'
css_dir = 'build'
sass_dir = 'src/styles'
images_dir = 'build/assets/images'
fonts_dir = 'build/assets/fonts'
relative_assets = true
line_comments = true
